version: 2
workflows:
  main:
    jobs:
    - build:
        -run: yes | sdkmanager --licenses
        working_directory: ~/code
        docker:
        - image: circleci/android:api-28-alpha
        environment:
          JVM_OPTS: -Xmx3200m
        steps:
        - checkout
        - restore_cache:
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        #      - run:
        #         name: Chmod permissions #if permission for Gradlew Dependencies fail, use this.
        #         command: sudo chmod +x ./gradlew
        - run:
            name: Download Dependencies
            command: ./gradlew androidDependencies
        - save_cache:
            paths:
            - ~/.gradle
            key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
        - run:
            name: Initial build
            command: ./gradlew clean assembleDebug --stacktrace
        - store_artifacts:
            path: app/build/outputs/apk/
            destination: apks/
    - publish-github-release:
        docker:
        - image: cibuilds/github:0.10
        steps:
        - attach_workspace:
            at: ./artifacts
        - run:
            name: "Publish Release on GitHub"
            command: |
              VERSION=$(my-binary --version)
              ghr -t ${GITHUB_API_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1}